[platformio]
default_envs = ch32v003f4p6_ch32fun
src_dir = src

[env:ch32v003f4p6_ch32fun]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V003F4P6
framework = ch32v003fun
upload_protocol = minichlink
monitor_speed = 115200
extra_scripts = post:tools/export_bin.py

build_flags =
  -std=gnu11
  -Ilib/ch32v00x/include
  -Ilib/gamelib/inc
  -DFUNCONF_USE_DEBUGPRINTF=0
  -DFUNCONF_USE_UARTPRINTF=0
  -DFUNCONF_NULL_PRINTF=0
