#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define CH32V003 1

#define FUNCONF_USE_HSI 1
#define FUNCONF_USE_HSE 0
#define FUNCONF_USE_PLL 1
#define FUNCONF_HSE_BYPASS 0
#define FUNCONF_SYSTEM_CORE_CLOCK 48000000

#define FUNCONF_USE_DEBUGPRINTF 0
#define FUNCONF_USE_UARTPRINTF 0
#define FUNCONF_NULL_PRINTF 0

#define FUNCONF_ENABLE_HPE 1
#define FUNCONF_SYSTICK_USE_HCLK 0

#endif
